apiVersion: v1
kind: Secret
metadata:
  name: payment-service-password
  namespace: kafka-lab
type: Opaque
stringData:
  password: "PaymentService2026!"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: payment-service
  namespace: kafka-lab
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: payment-service-password
          key: password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: order-events
          patternType: literal
        operations:
          - Read
          - Describe
        host: "*"
      - resource:
          type: group
          name: payment-service-group
          patternType: literal
        operations:
          - Read
        host: "*"
