# Il Secret contiene la password dell'utente
# Usiamo stringData invece di data così non dobbiamo encodare in base64
apiVersion: v1
kind: Secret
metadata:
  name: shipping-service-password
  namespace: kafka-lab
type: Opaque
stringData:
  password: "ShippingService2026!"
---
# Il KafkaUser definisce l'utente e i suoi permessi
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: shipping-service
  namespace: kafka-lab
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  # Autenticazione: come l'utente si identifica
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: shipping-service-password
          key: password
  # Autorizzazione: cosa l'utente può fare
  authorization:
    type: simple
    acls:
      # Permesso 1: Leggere da order-events
      # Il servizio shipping deve sapere quando arriva un nuovo ordine
      - resource:
          type: topic
          name: order-events
          patternType: literal    # literal = nome esatto, prefix = tutti i topic che iniziano con...
        operations:
          - Read
          - Describe
        host: "*"                  # Da qualsiasi IP
      
      # Permesso 2: Scrivere su shipping-events
      # Il servizio pubblica eventi quando una spedizione viene creata/aggiornata
      - resource:
          type: topic
          name: shipping-events
          patternType: literal
        operations:
          - Write
          - Describe
        host: "*"
      
      # Permesso 3: Usare un consumer group
      # Senza questo permesso, il consumer non può salvare gli offset
      - resource:
          type: group
          name: shipping-service-group
          patternType: literal
        operations:
          - Read
        host: "*"
