apiVersion: v1
kind: Secret
metadata:
  name: test-user-password
  namespace: kafka-lab
type: Opaque
stringData:
  password: "TestUser2026!"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: test-user
  namespace: kafka-lab
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: test-user-password
          key: password
