apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: utente-test
  namespace: kafka-lab
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: esercizio-01
          patternType: literal
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: gruppo-
          patternType: prefix
        operations:
          - Read
